server:
  port : 3000
logging:
  level:
    root: INFO
url:
  host: takehome.io
  twitter: https://takehome.io/twitter
  facebook: https://takehome.io/facebook
  instagram: https://takehome.io/instagram